-- Generated by scripts/gen-import-wo-sql.mjs from the Railway portal's data/work_orders.json.
-- 4 work orders, 3 visits. Safe to re-run (existing ids are left untouched).
insert into public.work_orders
  (id, wo_number, title, location, type, priority, status, details, photos, created_by, source, slack_channel, slack_ts, created_at, updated_at)
values
('WO-2026-0004', 'WO-2026-0004', 'Slack request cold g2580', '900 Sylvan Ave', 'Cold Call', 'Normal', 'Open', 'Fixed vac g74', '[]', 'Christian Dell''Andrino', null, null, null, '2026-07-06T14:54:58.814Z', '2026-07-06T14:56:10.698Z'),
('WO-2026-0003', 'WO-2026-0003', 'pre-action drain smell 2nd floor noc', '900 Sylvan Ave', 'Other', 'Normal', 'In Progress', 'smell coming from pre-action drain in 2nd floor noc', '[]', 'Sean Fanning', null, null, null, '2026-05-14T14:03:31.296Z', '2026-05-14T14:03:31.296Z'),
('WO-2026-0002', 'WO-2026-0002', 'pre-action drain smell 2nd floor noc', '900 Sylvan Ave', 'Other', 'Normal', 'Completed', 'smell coming from drain in noc pre-action closet', '[]', 'Sean Fanning', null, null, null, '2026-05-14T14:01:55.485Z', '2026-05-14T14:05:19.030Z'),
('WO-2026-0001', 'WO-2026-0001', 'kitchen sink loose', '900 Sylvan Ave', 'Repair', 'Normal', 'On Hold', 'new faucet on order but current one is in service not leaking', '[]', 'Sean Fanning', null, null, null, '2026-05-14T13:59:47.375Z', '2026-05-14T14:00:39.078Z')
on conflict (id) do nothing;

insert into public.work_order_visits
  (id, work_order_id, visit_date, tech, hours, notes, photos, logged_by, logged_at)
values
('WO-2026-0004-v1', 'WO-2026-0004', '2026-07-06', 'Christian Dell''Andrino', 1, 'Repaired', '[]', 'Christian Dell''Andrino', '2026-07-06T14:56:10.207Z'),
('WO-2026-0002-v1', 'WO-2026-0002', '2026-05-14', 'Robert R', 0.5, 'Primed drain and added deodorizer', '[]', 'Robert R', '2026-05-14T14:05:04.656Z'),
('WO-2026-0001-v1', 'WO-2026-0001', '2026-05-14', 'Sean Fanning christian D, Robert R', 0.5, 'part on order', '[]', 'Sean Fanning christian D, Robert R', '2026-05-14T14:00:38.857Z')
on conflict (id) do nothing;

select 'Work orders imported: ' || count(*) || ' orders, next number will be WO-' || extract(year from now())::int || '-' ||
       lpad(((select coalesce(last, 0) from public.wo_counters where year = extract(year from now())::int) + 1)::text, 4, '0') as result
  from public.work_orders;
